baseURL: "https://emiliendilly.github.io" 
title: Émilien Dilly
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: News
          url: courses/
        - name: Papers
          url: papers/
        - name: Projects
          url: projects/
        - name: Talks
          url: talks/

params:
    description: "This website hosts Emilien Dilly work presentation."
    author: Émilien Dilly
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    customCSS: ["css/custom.css"]
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Émilien Dilly
          subtitle: "Post-doc at Laboratoire Interdisciplinaire de Physique at Université Grenoble Alpes."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: News
              url: courses/
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: Talks
              url: talks/




    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:emilien.dilly@univ-grenoble-alpes.fr
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=B3NCJ8kAAAAJ&hl=fr
        - name: GitHub
          url: https://github.com/emiliendilly
        - name: LinkedIn
          url: https://www.linkedin.com/in/émilien-dilly-5b2a80196


    assets:
        disableScrollBarStyle: false
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Émilien Dilly"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
